# Generated by Django 3.1.7 on 2021-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210426_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
