# Generated by Django 3.1.7 on 2021-05-15 20:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210502_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('type', models.TextField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.TextField(blank=True, max_length=255)),
                ('location', models.TextField(blank=True, max_length=255)),
                ('town', models.TextField(blank=True, max_length=255)),
                ('district', models.TextField(blank=True, max_length=255)),
                ('country', models.TextField(blank=True, max_length=255)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.restaurant'),
        ),
    ]
