# Generated by Django 3.1.7 on 2021-05-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210515_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
