# Generated by Django 3.1.7 on 2021-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210515_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
