# Generated by Django 3.1.7 on 2021-05-22 13:23

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210522_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.restaurant'),
        ),
    ]
