# Generated by Django 3.1.7 on 2021-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210511_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='aa.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
