# Generated by Django 3.1.7 on 2021-05-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210511_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.menu'),
        ),
    ]
